//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiciosWebSoap")]
    public interface ServiciosWebSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WinFormsApp.ServiceReference1.HelloWorldResponse HelloWorld(WinFormsApp.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WinFormsApp.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WinFormsApp.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento FechayHoraResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FechayHora", ReplyAction="*")]
        WinFormsApp.ServiceReference1.FechayHoraResponse FechayHora(WinFormsApp.ServiceReference1.FechayHoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FechayHora", ReplyAction="*")]
        System.Threading.Tasks.Task<WinFormsApp.ServiceReference1.FechayHoraResponse> FechayHoraAsync(WinFormsApp.ServiceReference1.FechayHoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularSueldo", ReplyAction="*")]
        double CalcularSueldo(double sueldoBasico, double antiguedad, double horasExtras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularSueldo", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CalcularSueldoAsync(double sueldoBasico, double antiguedad, double horasExtras);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WinFormsApp.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WinFormsApp.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WinFormsApp.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WinFormsApp.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FechayHoraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FechayHora", Namespace="http://tempuri.org/", Order=0)]
        public WinFormsApp.ServiceReference1.FechayHoraRequestBody Body;
        
        public FechayHoraRequest() {
        }
        
        public FechayHoraRequest(WinFormsApp.ServiceReference1.FechayHoraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FechayHoraRequestBody {
        
        public FechayHoraRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FechayHoraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FechayHoraResponse", Namespace="http://tempuri.org/", Order=0)]
        public WinFormsApp.ServiceReference1.FechayHoraResponseBody Body;
        
        public FechayHoraResponse() {
        }
        
        public FechayHoraResponse(WinFormsApp.ServiceReference1.FechayHoraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FechayHoraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FechayHoraResult;
        
        public FechayHoraResponseBody() {
        }
        
        public FechayHoraResponseBody(string FechayHoraResult) {
            this.FechayHoraResult = FechayHoraResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosWebSoapChannel : WinFormsApp.ServiceReference1.ServiciosWebSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosWebSoapClient : System.ServiceModel.ClientBase<WinFormsApp.ServiceReference1.ServiciosWebSoap>, WinFormsApp.ServiceReference1.ServiciosWebSoap {
        
        public ServiciosWebSoapClient() {
        }
        
        public ServiciosWebSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosWebSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosWebSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosWebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinFormsApp.ServiceReference1.HelloWorldResponse WinFormsApp.ServiceReference1.ServiciosWebSoap.HelloWorld(WinFormsApp.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WinFormsApp.ServiceReference1.HelloWorldRequest inValue = new WinFormsApp.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WinFormsApp.ServiceReference1.HelloWorldRequestBody();
            WinFormsApp.ServiceReference1.HelloWorldResponse retVal = ((WinFormsApp.ServiceReference1.ServiciosWebSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WinFormsApp.ServiceReference1.HelloWorldResponse> WinFormsApp.ServiceReference1.ServiciosWebSoap.HelloWorldAsync(WinFormsApp.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WinFormsApp.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WinFormsApp.ServiceReference1.HelloWorldRequest inValue = new WinFormsApp.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WinFormsApp.ServiceReference1.HelloWorldRequestBody();
            return ((WinFormsApp.ServiceReference1.ServiciosWebSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinFormsApp.ServiceReference1.FechayHoraResponse WinFormsApp.ServiceReference1.ServiciosWebSoap.FechayHora(WinFormsApp.ServiceReference1.FechayHoraRequest request) {
            return base.Channel.FechayHora(request);
        }
        
        public string FechayHora() {
            WinFormsApp.ServiceReference1.FechayHoraRequest inValue = new WinFormsApp.ServiceReference1.FechayHoraRequest();
            inValue.Body = new WinFormsApp.ServiceReference1.FechayHoraRequestBody();
            WinFormsApp.ServiceReference1.FechayHoraResponse retVal = ((WinFormsApp.ServiceReference1.ServiciosWebSoap)(this)).FechayHora(inValue);
            return retVal.Body.FechayHoraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WinFormsApp.ServiceReference1.FechayHoraResponse> WinFormsApp.ServiceReference1.ServiciosWebSoap.FechayHoraAsync(WinFormsApp.ServiceReference1.FechayHoraRequest request) {
            return base.Channel.FechayHoraAsync(request);
        }
        
        public System.Threading.Tasks.Task<WinFormsApp.ServiceReference1.FechayHoraResponse> FechayHoraAsync() {
            WinFormsApp.ServiceReference1.FechayHoraRequest inValue = new WinFormsApp.ServiceReference1.FechayHoraRequest();
            inValue.Body = new WinFormsApp.ServiceReference1.FechayHoraRequestBody();
            return ((WinFormsApp.ServiceReference1.ServiciosWebSoap)(this)).FechayHoraAsync(inValue);
        }
        
        public double CalcularSueldo(double sueldoBasico, double antiguedad, double horasExtras) {
            return base.Channel.CalcularSueldo(sueldoBasico, antiguedad, horasExtras);
        }
        
        public System.Threading.Tasks.Task<double> CalcularSueldoAsync(double sueldoBasico, double antiguedad, double horasExtras) {
            return base.Channel.CalcularSueldoAsync(sueldoBasico, antiguedad, horasExtras);
        }
    }
}
